spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - "file:///C:/Users/user/Pictures/MonoUzbBotPhotos/"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8088}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    webAppUrl: ${TELEGRAM_WEBAPP_URL}

jwt:
  secret: "supersecretkeythatshouldbeatleast32byteslong123"

#8114214391:AAH87KGeNzym0fBU41MSE1h80GfW1jo9cuc
#monouzbekistanbot_bot
#https://monouzb:onrender:com